spring.application.name=server

server.port=${APP_PORT:8080}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/app_db}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true



# email
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.name=${EMAIL_NAME}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# redis
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}


# jwt
jwt.secret=${JWT_SECRET:}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION:}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION:}